version: '3'
services:
  webapp:
    build: .
    image: vue-workspace-03
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    command: /bin/sh